name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt bats jq gawk git
          # TODO: replace the commit hash below with the trusted commit for the gitleaks install script
          curl -sSfL https://raw.githubusercontent.com/gitleaks/gitleaks/0000000000000000000000000000000000000000/scripts/install.sh | \
            bash -s -- -b /usr/local/bin
          # TODO: replace the commit hash and version below with the desired syft release
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/0000000000000000000000000000000000000000/install.sh | sh -s -- -b /usr/local/bin v0.0.0
          syft version
          gitleaks version

      - name: Format check (shfmt)
        run: |
          set -euxo pipefail
          shfmt -d .

      - name: Lint (shellcheck)
        run: |
          set -euxo pipefail
          find . -type f -name "*.sh" -print0 | xargs -0 -I{} shellcheck --severity=style --external-sources -f gcc {}

      - name: Secret scan (gitleaks)
        run: |
          set -euxo pipefail
          gitleaks detect --no-git -v --redact

      - name: Run tests (bats)
        run: |
          set -euxo pipefail
          if compgen -G "tests/*.bats" > /dev/null; then
            bats tests
          else
            echo "No Bats tests found; skipping."
          fi

      - name: Build SBOM (syft)
        run: |
          set -euxo pipefail
          syft dir:. -o spdx-json=sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json
