name: ci
on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          scandir: './'
        env:
          SHELLCHECK_OPTS: '-S warning'

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ktomk/setup-shfmt@v10
        with: { shfmt: v3.7.0 }
      - name: Check formatting
        run: shfmt -d -i 2 -ci -sr .

  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bats
        uses: bats-core/bats-action@2.0.0
      - name: Run tests
        run: bats -r tests

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: "true"
          GITLEAKS_ENABLE_SUMMARY: "true"

  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint GitHub Actions
        uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -color

