name: Release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify tag matches VERSION
        run: |
          set -euo pipefail
          if [ -f VERSION ]; then
            v="$(awk '{\$1=\$1};1' VERSION)"
            if [ "v${v}" != "${GITHUB_REF_NAME}" ]; then
              echo "Tag ${GITHUB_REF_NAME} does not match VERSION v${v}" >&2
              exit 1
            fi
          fi

      - name: Build dist
        run: |
          set -euxo pipefail
          rm -rf dist && mkdir -p dist
          tar -czf "dist/vios-autoconfig-${GITHUB_REF_NAME}.tar.gz" lib maps scripts README.md LICENSE

      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Release
        uses: softprops/action-gh-release@d8199f1870e7d2834e97e1f38da813e1ea977473
        with:
          files: dist/*
          generate_release_notes: true
